org:
  fuin:
    bupdater:
      includes:
        - "ch.qos.logback:logback-classic"
        - "ch.qos.logback:logback-core"
        - "com.fasterxml.jackson.core:jackson-annotations"
        - "com.fasterxml.jackson.core:jackson-core"
        - "com.fasterxml.jackson.core:jackson-databind"
        - "com.fasterxml.jackson.datatype:jackson-datatype-jsr310"
        - "com.google.auto.service:auto-service"
        - "com.google.auto.service:auto-service-annotations"
        - "com.google.code.gson:gson"
        - "com.google.googlejavaformat:google-java-format"
        - "com.google.guava:guava"
        - "com.sun.mail:jakarta.mail"
        - "com.tngtech.archunit:archunit"
        - "com.tngtech.archunit:archunit-junit5"
        - "commons-codec:commons-codec"
        - "commons-io:commons-io"
        - "info.cukes:gherkin"
        - "io.cucumber:cucumber-java"
        - "io.cucumber:cucumber-junit-platform-engine"
        - "io.github.threeten-jaxb:threeten-jaxb-core"
        - "io.grpc:grpc-api"
        - "io.kurrent:kurrentdb-client"
        - "io.quarkus:quarkus-core"
        - "io.quarkus:quarkus-hibernate-orm"
        - "io.quarkus:quarkus-junit5"
        - "io.quarkus:quarkus-junit5-mockito"
        - "io.quarkus:quarkus-narayana-jta"
        - "io.quarkus:quarkus-scheduler"
        - "io.quarkus:quarkus-scheduler-api"
        - "io.quarkus:quarkus-test-common"
        - "io.quarkus.arc:arc"
        - "io.smallrye:jandex"
        - "io.toolisticon.cute:cute"
        - "jakarta.activation:jakarta.activation-api"
        - "jakarta.annotation:jakarta.annotation-api"
        - "jakarta.el:jakarta.el-api"
        - "jakarta.enterprise:jakarta.enterprise.cdi-api"
        - "jakarta.inject:jakarta.inject-api"
        - "jakarta.json:jakarta.json-api"
        - "jakarta.json.bind:jakarta.json.bind-api"
        - "jakarta.mail:jakarta.mail-api"
        - "jakarta.persistence:jakarta.persistence-api"
        - "jakarta.transaction:jakarta.transaction-api"
        - "jakarta.validation:jakarta.validation-api"
        - "jakarta.xml.bind:jakarta.xml.bind-api"
        - "net.javacrumbs.json-unit:json-unit-fluent"
        - "nl.jqno.equalsverifier:equalsverifier"
        - "org.apache.commons:commons-lang3"
        - "org.apache.httpcomponents:httpclient"
        - "org.apache.velocity:velocity-engine-core"
        - "org.assertj:assertj-core"
        - "org.eclipse:yasson"
        - "org.eclipse.microprofile.config:microprofile-config-api"
        - "org.eclipse.microprofile.openapi:microprofile-openapi-api"
        - "org.eclipse.persistence:org.eclipse.persistence.jpa"
        - "org.glassfish:jakarta.json"
        - "org.glassfish.expressly:expressly"
        - "org.glassfish.jaxb:jaxb-runtime"
        - "org.hibernate.orm:hibernate-core"
        - "org.hibernate.validator:hibernate-validator"
        - "org.hsqldb:hsqldb"
        - "org.jboss.logging:jboss-logging"
        - "org.jboss.weld.se:weld-se-core"
        - "org.jooq:joor"
        - "org.junit.jupiter:junit-jupiter"
        - "org.junit.jupiter:junit-jupiter-engine"
        - "org.junit.platform:junit-platform-suite-api"
        - "org.junit.platform:junit-platform-suite-engine"
        - "org.mariadb.jdbc:mariadb-java-client"
        - "org.mockito:mockito-core"
        - "org.mockito:mockito-junit-jupiter"
        - "org.ow2.asm:asm"
        - "org.ow2.asm:asm-commons"
        - "org.slf4j:slf4j-api"
        - "org.springframework:spring-context"
        - "org.springframework:spring-core"
        - "org.springframework:spring-orm"
        - "org.springframework:spring-tx"
        - "org.springframework.boot:spring-boot"
        - "org.testcontainers:mariadb"
        - "org.xmlunit:xmlunit-core"
      fixedVersions:
        - "jakarta.annotation:jakarta.annotation-api:3.0.0"
      frameworks:
        - "io.quarkus:quarkus-bom:3.23.4"
        - "org.springframework.boot:spring-boot-dependencies:3.5.14"
      pom-file: app/src/test/resources/pom.xml
      printType: failed
      printFile: app/target/app-test.html
      strategy: highest
